services:
  - type: web
    name: volleyball-live-scorer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 --threads 2 --timeout 60 wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
